services:
  app:
    build:
      context: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started # Ensure the app starts after the db container is ready

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
